### ISSUE TITLE
the engine.h cannot find on windows?  you may test this on ubuntu?

### ISSUE THREAD

**Issue by SyGoing** [mview/mxnet-samples#1]
Did you test it on ubuntu,since you include engine.h. I just build it on windows, but cannot find the engine.h, so the speed is not well, it cost 100ms on windows when I Remove it. could please implete it on windows? if so, thank you very much

**Comment by joey2014** [comment]
Yes, I test it on ubuntu.  The low performance isn't related to engine.h , is it? Can you try the python version https://github.com/pangyupo/mxnet_mtcnn_face_detection  first?

**Comment by SyGoing** [comment]
I'll show you the project.  since there'is no engine.h, I guess it ralated to that.   so, your conputer may be better, I test it on windows(cpu i7 7700,not GPU)
